name: calendar
description: "A new Flutter project."

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-117.0.dev

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core:
  cloud_firestore:
  cupertino_icons: ^1.0.8
  intl:
  syncfusion_flutter_calendar:
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_screenutil: ^5.9.3
  onesignal_flutter: ^5.3.2
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
